#!/usr/bin/env bash

set -e

# Pull the latest changes from the repository
git pull --prune

# Run the installation script
./dotbot_install

# Update the submodules
git submodule update --init --remote
