#!/usr/bin/env bash

set -e

# Pull the latest changes from the repository
git pull --prune

# Update the submodules
git submodule update --init --recursive --remote

# Run the installation script
./dotbot_install
