name: Test configuration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  generate-matrix:
    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate matrix from tests/cases/*.yaml
        id: set-matrix
        run: |
          matrix="$(yq eval-all -o=json '[.cases[]] as $i ireduce ([]; . + $i)' tests/cases/*.yaml | jq -c '{include: .}')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  test-configuration:
    name: ${{ matrix.name }}
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run case ${{ matrix.name }}
        env:
          CONTAINER_RUNTIME: docker
        run: |
          ./tests/run.sh "${{ matrix.name }}"
