name: Test configuration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test-configuration:
    name: ${{ matrix.distro.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - image: fedora:latest
            name: fedora
          - image: ubuntu:latest
            name: ubuntu
          - image: alpine:latest
            name: alpine
    container:
      image: ${{ matrix.distro.image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create test user
        run: |
          if [ "${{ matrix.distro.name }}" = "fedora" ]; then
            useradd -m testuser
            dnf install -y util-linux
          elif [ "${{ matrix.distro.name }}" = "ubuntu" ]; then
            useradd -m testuser
          elif [ "${{ matrix.distro.name }}" = "alpine" ]; then
            adduser -D testuser
          fi

      - name: Test configuration
        run: |
          su testuser
          cp -r . ~/${{ github.event.repository.name }}
          cd ~/${{ github.event.repository.name }}
          ./install.sh
